version: 2

jobs:
  build:
    docker:
      - image: quay.io/rust-lang-ja/circleci:rust-by-example-mdbook-0.3.5
    parallelism: 1
    steps:
      - checkout
      # Remove .gitconfig added by Circle CI as cargo doesn't support ssh authorization
      - run: rm -f ~/.gitconfig
      - run: rm -rf docs
      - run: mdbook -V
      - run: mdbook build
      - run: mdbook test
      - store_artifacts:
          path: docs
      - deploy:
          name: If master branch, publish to GitHub Page
          command: |
            if [ "x_${CIRCLE_BRANCH}" == "x_master" ]; then
              git config user.name "bn-e (CircleCI)"
              git config user.email "bn-e@hibaridb.org"
              ./tools/circleci/push-to-master.sh
            fi
